// Generated by tools/decode_jimaku.py - do not edit by hand.
//
// Biohazard Director's Cut (SLPS_009.98) FMV subtitle data. Regenerate with:
//   python tools/decode_jimaku.py --iso <BiohazardDirectrorsCut.img> \
//       --exe assets/PSX_JPNDC/SLPS_009.98 --track <0|1|2> --out assets/JPN/data
//
// Source of truth: the JPN resident exe's subtitle track directory
// (DAT_80090490, 8 bytes per track: u32 cue-table pointer, u32 CD file index)
// and the disc's JIMAKU00/01/02.RGB (CD file indices 18/19/20).
#pragma once

struct FmvSubtitleCue {
    short startFrame;   // +0x00  movie frame the cue switches on
    short duration;     // +0x04  frames it stays up
    short line;         // +0x08  first line inside the jimakuNN.png set
    short lines;        // +0x0A  line count; raster height = lines * 18
    short x;            // +0x0C  destination x in the 320x240 overlay
    short y;            // +0x0E  destination y
};

// One greyscale PNG per track, 320 wide, 18 rows per line.
// Line counts match the disc: JIMAKU00 = 23, JIMAKU01 = 7, JIMAKU02 = 5.
static const short kFmvSubtitleLineCount[3] = { 23, 7, 5 };

// Track 0 -> JIMAKU00.RGB (prologue / main title FMV)
static const FmvSubtitleCue kFmvSubtitleCues0[] = {
    {  125,   60,  0, 1,   0, 205 },
    {  195,   65,  1, 2,   0, 187 },
    {  260,   97,  3, 2,   0, 187 },
    {  435,   59,  5, 2,   0, 187 },
    {  495,  105,  7, 2,   0, 187 },
    {  615,   40,  9, 1,   0, 196 },
    {  655,   30, 10, 1,   0, 196 },
    {  720,   30, 11, 1,   0, 196 },
    {  982,   53, 12, 2,   0, 187 },
    { 1035,   60, 14, 1,   0, 196 },
    { 1105,   60, 15, 1,   0, 196 },
    { 1342,   30, 16, 1,   0, 196 },
    { 2195,   33, 18, 1,   0, 196 },
    { 2475,   27, 19, 1,   0, 196 },
    { 2670,   55, 20, 1,   0, 196 },
    { 2725,   65, 21, 1,   0, 196 },
    { 2790,   30, 22, 1,   0, 196 },
};
static const short kFmvSubtitleCueCount0 = 17;

// Track 1 -> JIMAKU02.RGB
static const FmvSubtitleCue kFmvSubtitleCues1[] = {
    {  334,   44,  0, 1,   0, 196 },
    {  379,   44,  1, 1,   0, 196 },
    {  424,   44,  2, 1,   0, 196 },
    {  469,   44,  3, 1,   0, 196 },
    {  514,   44,  4, 1,   0, 196 },
};
static const short kFmvSubtitleCueCount1 = 5;

// Track 2 -> JIMAKU01.RGB
static const FmvSubtitleCue kFmvSubtitleCues2[] = {
    {  372,   30,  0, 1,   0, 196 },
    {  408,   44,  1, 1,   0, 196 },
    {  453,   29,  2, 1,   0, 196 },
    {  483,   45,  3, 1,   0, 196 },
    {  555,   30,  4, 1,   0, 196 },
    {  570,   44,  5, 1,   0, 196 },
    {  615,   45,  6, 1,   0, 196 },
};
static const short kFmvSubtitleCueCount2 = 7;
