// ArrangeSoundRows.cpp - GENERATED by tools/gen_dc_arrange_sound_rows.py.
// Do not edit by hand; edit the generator and re-run it.
//
// Where a DC room's enemy sound bank does not match what the port loads for it,
// mined from the RDT's own embedded VAB (RDT+0x88/0x8C/0x90). Two kinds:
//
//   DC_SND_ARRANGE  the arrange RDT's bank differs from the base room's, so the
//                   entry applies only while the arrange file is loaded. A NULL
//                   name CLEARS the slot - the DC really does leave it empty,
//                   because what ADVANCED puts there has fewer sounds than what
//                   it replaces.
//   DC_SND_ANY_DC   the room has no arrange RDT at all; it keeps its own file in
//                   every mode and the PC's g_RoomSndData row simply has nothing
//                   for the enemy the DC spawns in it. Same file either way, so
//                   the entry applies whenever DC mode is on.
//
// Only room 0 of each pair is mined: every room here has the same bank in both
// character variants.
#include "ArrangeSoundRows.h"

static const DcArrangeSndSlot g_dcArrangeSndSlots[] = {
    // room 101 - donor ROOM1080
    { 0, 0x01,  0, DC_SND_ARRANGE, "cer_foot"  },   // was z_taore
    { 0, 0x01,  1, DC_SND_ARRANGE, "cer_taoA"  },   // was z_ftL
    { 0, 0x01,  2, DC_SND_ARRANGE, "cer_unar"  },   // was z_ftR
    { 0, 0x01,  3, DC_SND_ARRANGE, "cer_bite"  },   // was z_kamu
    { 0, 0x01,  4, DC_SND_ARRANGE, "cer_cryA"  },   // was z_k02
    { 0, 0x01,  5, DC_SND_ARRANGE, "cer_taoB"  },   // was z_k01
    { 0, 0x01,  6, DC_SND_ARRANGE, "cer_jkMX"  },   // was z_head
    { 0, 0x01,  7, DC_SND_ARRANGE, "cer_kamu"  },   // was z_haki
    { 0, 0x01,  8, DC_SND_ARRANGE, "cer_cryB"  },   // was z_sanj
    { 0, 0x01,  9, DC_SND_ARRANGE, "cer_runMX" },   // was z_k03
    { 0, 0x01, 23, DC_SND_ARRANGE, "glass"     },   // was nothing
    { 0, 0x01, 24, DC_SND_ARRANGE, "glass"     },   // was nothing
    // room 113 - donor ROOM1090
    { 0, 0x13,  0, DC_SND_ARRANGE, "z_taore"   },   // was nothing
    { 0, 0x13,  1, DC_SND_ARRANGE, "z_ftL"     },   // was nothing
    { 0, 0x13,  2, DC_SND_ARRANGE, "z_ftR"     },   // was nothing
    { 0, 0x13,  3, DC_SND_ARRANGE, "z_kamu"    },   // was nothing
    { 0, 0x13,  4, DC_SND_ARRANGE, "z_osou"    },   // was nothing
    { 0, 0x13,  5, DC_SND_ARRANGE, "z_unaruA"  },   // was nothing
    { 0, 0x13,  6, DC_SND_ARRANGE, "z_head"    },   // was nothing
    { 0, 0x13,  7, DC_SND_ARRANGE, "z_Hkick"   },   // was nothing
    { 0, 0x13,  8, DC_SND_ARRANGE, "z_Ugoron"  },   // was nothing
    { 0, 0x13,  9, DC_SND_ARRANGE, 0           },   // was nothing
    { 0, 0x13, 23, DC_SND_ARRANGE, "z_taore"   },   // was bathMIX
    // room 212 - donor ROOM1090
    { 1, 0x12,  0, DC_SND_ARRANGE, "z_taore"   },   // was RVcar1
    { 1, 0x12,  1, DC_SND_ARRANGE, "z_ftL"     },   // was RVpat
    { 1, 0x12,  2, DC_SND_ARRANGE, "z_ftR"     },   // was RVcar2
    { 1, 0x12,  3, DC_SND_ARRANGE, "z_kamu"    },   // was RVwing1
    { 1, 0x12,  4, DC_SND_ARRANGE, "z_osou"    },   // was RVwing2
    { 1, 0x12,  5, DC_SND_ARRANGE, "z_unaruA"  },   // was RVfryed
    { 1, 0x12,  6, DC_SND_ARRANGE, "z_head"    },   // was nothing
    { 1, 0x12,  7, DC_SND_ARRANGE, "z_Hkick"   },   // was nothing
    { 1, 0x12,  8, DC_SND_ARRANGE, "z_Ugoron"  },   // was nothing
    { 1, 0x12,  9, DC_SND_ARRANGE, "z_unaruB"  },   // was nothing
    { 1, 0x12, 10, DC_SND_ARRANGE, "z_taore"   },   // was nothing
    { 1, 0x12, 24, DC_SND_ARRANGE, 0           },   // was RVpatA
    { 1, 0x12, 25, DC_SND_ARRANGE, 0           },   // was RVpatB
    // room 405 - donor ROOM4040
    { 3, 0x05,  0, DC_SND_ARRANGE, "kuasi_A"   },   // was bee4_ed
    { 3, 0x05,  1, DC_SND_ARRANGE, "kuasi_B"   },   // was hatinage
    { 3, 0x05,  2, DC_SND_ARRANGE, "kuasi_C"   },   // was bee_fumu
    { 3, 0x05,  3, DC_SND_ARRANGE, "sp_rakk"   },   // was nothing
    { 3, 0x05,  4, DC_SND_ARRANGE, "sp_atck"   },   // was nothing
    { 3, 0x05,  5, DC_SND_ARRANGE, "sp_bomb"   },   // was nothing
    { 3, 0x05,  6, DC_SND_ARRANGE, "sp_fumu"   },   // was nothing
    { 3, 0x05,  7, DC_SND_ARRANGE, "sp_Doku"   },   // was nothing
    { 3, 0x05,  8, DC_SND_ARRANGE, "sp_sanj2"  },   // was nothing
    // room 507 - donor ROOM1030
    { 4, 0x07,  0, DC_SND_ARRANGE, "z_taore"   },   // was nothing
    { 4, 0x07,  1, DC_SND_ARRANGE, "z_ftL"     },   // was nothing
    { 4, 0x07,  2, DC_SND_ARRANGE, "z_ftR"     },   // was nothing
    { 4, 0x07,  3, DC_SND_ARRANGE, "z_kamu"    },   // was nothing
    { 4, 0x07,  4, DC_SND_ARRANGE, "ze_tomo2"  },   // was nothing
    { 4, 0x07,  5, DC_SND_ARRANGE, "ze_tomo1"  },   // was nothing
    { 4, 0x07,  6, DC_SND_ARRANGE, "z_head"    },   // was nothing
    { 4, 0x07,  7, DC_SND_ARRANGE, "z_Hkick"   },   // was nothing
    { 4, 0x07,  8, DC_SND_ARRANGE, "z_Ugoron"  },   // was nothing
    { 4, 0x07,  9, DC_SND_ARRANGE, "ze_tomo3"  },   // was nothing
    // room 604 - donor ROOM4040
    { 5, 0x04,  0, DC_SND_ARRANGE, "kuasi_A"   },   // was HU_walkA
    { 5, 0x04,  1, DC_SND_ARRANGE, "kuasi_B"   },   // was HU_walkB
    { 5, 0x04,  2, DC_SND_ARRANGE, "kuasi_C"   },   // was HU_jump
    { 5, 0x04,  3, DC_SND_ARRANGE, "sp_rakk"   },   // was HU_att
    { 5, 0x04,  4, DC_SND_ARRANGE, "sp_atck"   },   // was HU_land
    { 5, 0x04,  5, DC_SND_ARRANGE, "sp_bomb"   },   // was HU_smash
    { 5, 0x04,  6, DC_SND_ARRANGE, "sp_fumu"   },   // was HU_dam
    { 5, 0x04,  7, DC_SND_ARRANGE, "sp_Doku"   },   // was HU_Nout
    { 5, 0x04,  8, DC_SND_ARRANGE, "sp_sanj2"  },   // was nothing
    // room 607 - donor ROOM1070
    { 5, 0x07,  0, DC_SND_ARRANGE, "z_taore"   },   // was nothing
    { 5, 0x07,  1, DC_SND_ARRANGE, "z_ftL"     },   // was nothing
    { 5, 0x07,  2, DC_SND_ARRANGE, "z_ftR"     },   // was nothing
    { 5, 0x07,  3, DC_SND_ARRANGE, "z_kamu"    },   // was nothing
    { 5, 0x07,  4, DC_SND_ARRANGE, "z_aoya02"  },   // was nothing
    { 5, 0x07,  5, DC_SND_ARRANGE, "z_aoya01"  },   // was nothing
    { 5, 0x07,  6, DC_SND_ARRANGE, "z_head"    },   // was nothing
    { 5, 0x07,  7, DC_SND_ARRANGE, "z_Hkick"   },   // was nothing
    { 5, 0x07,  8, DC_SND_ARRANGE, "z_Ugoron"  },   // was nothing
    { 5, 0x07,  9, DC_SND_ARRANGE, "z_aoya03"  },   // was nothing
    // room 613 - donor ROOM1090
    { 5, 0x13,  0, DC_SND_ARRANGE, "z_taore"   },   // was nothing
    { 5, 0x13,  1, DC_SND_ARRANGE, "z_ftL"     },   // was nothing
    { 5, 0x13,  2, DC_SND_ARRANGE, "z_ftR"     },   // was nothing
    { 5, 0x13,  3, DC_SND_ARRANGE, "z_kamu"    },   // was nothing
    { 5, 0x13,  4, DC_SND_ARRANGE, "z_osou"    },   // was nothing
    { 5, 0x13,  5, DC_SND_ARRANGE, "z_unaruA"  },   // was nothing
    { 5, 0x13,  6, DC_SND_ARRANGE, "z_head"    },   // was nothing
    { 5, 0x13,  7, DC_SND_ARRANGE, "z_Hkick"   },   // was nothing
    { 5, 0x13,  8, DC_SND_ARRANGE, "z_Ugoron"  },   // was nothing
    { 5, 0x13,  9, DC_SND_ARRANGE, 0           },   // was nothing
    { 5, 0x13, 23, DC_SND_ARRANGE, "z_taore"   },   // was bathMIX
    // room 703 - donor ROOM2030
    { 6, 0x03,  0, DC_SND_ARRANGE, "z_taore"   },   // was nothing
    { 6, 0x03,  1, DC_SND_ARRANGE, "z_ftL"     },   // was nothing
    { 6, 0x03,  2, DC_SND_ARRANGE, "z_ftR"     },   // was nothing
    { 6, 0x03,  3, DC_SND_ARRANGE, "z_kamu"    },   // was nothing
    { 6, 0x03,  4, DC_SND_ARRANGE, "z_osou"    },   // was nothing
    { 6, 0x03,  5, DC_SND_ARRANGE, "z_unaruA"  },   // was nothing
    { 6, 0x03,  6, DC_SND_ARRANGE, "z_head"    },   // was nothing
    { 6, 0x03,  7, DC_SND_ARRANGE, "z_haki"    },   // was nothing
    { 6, 0x03,  8, DC_SND_ARRANGE, "z_sanj"    },   // was nothing
    { 6, 0x03,  9, DC_SND_ARRANGE, "z_unaruB"  },   // was nothing
    // room 712 - donor ROOM1090
    { 6, 0x12,  0, DC_SND_ARRANGE, "z_taore"   },   // was RVcar1
    { 6, 0x12,  1, DC_SND_ARRANGE, "z_ftL"     },   // was RVpat
    { 6, 0x12,  2, DC_SND_ARRANGE, "z_ftR"     },   // was RVcar2
    { 6, 0x12,  3, DC_SND_ARRANGE, "z_kamu"    },   // was RVwing1
    { 6, 0x12,  4, DC_SND_ARRANGE, "z_osou"    },   // was RVwing2
    { 6, 0x12,  5, DC_SND_ARRANGE, "z_unaruA"  },   // was RVfryed
    { 6, 0x12,  6, DC_SND_ARRANGE, "z_head"    },   // was nothing
    { 6, 0x12,  7, DC_SND_ARRANGE, "z_Hkick"   },   // was nothing
    { 6, 0x12,  8, DC_SND_ARRANGE, "z_Ugoron"  },   // was nothing
    { 6, 0x12,  9, DC_SND_ARRANGE, "z_unaruB"  },   // was nothing
    { 6, 0x12, 10, DC_SND_ARRANGE, "z_taore"   },   // was nothing
    { 6, 0x12, 24, DC_SND_ARRANGE, 0           },   // was RVpatA
    { 6, 0x12, 25, DC_SND_ARRANGE, 0           },   // was RVpatB
    // room 718 - donor ROOM1170
    { 6, 0x18,  0, DC_SND_ARRANGE, "RVcar1"    },   // was nothing
    { 6, 0x18,  1, DC_SND_ARRANGE, "RVpat"     },   // was nothing
    { 6, 0x18,  2, DC_SND_ARRANGE, "RVcar2"    },   // was nothing
    { 6, 0x18,  3, DC_SND_ARRANGE, "RVwing1"   },   // was nothing
    { 6, 0x18,  4, DC_SND_ARRANGE, "RVwing2"   },   // was nothing
    { 6, 0x18,  5, DC_SND_ARRANGE, "RVfryed"   },   // was nothing
    { 6, 0x18,  6, DC_SND_ARRANGE, "RVpatA"    },   // was nothing
    { 6, 0x18,  7, DC_SND_ARRANGE, "RVpatB"    },   // was nothing
    { 6, 0x18, 24, DC_SND_ARRANGE, "glass"     },   // was nothing
    // room 71A
    { 6, 0x1A, 10, DC_SND_ARRANGE, "He_walkA"  },   // was z_taore
    { 6, 0x1A, 11, DC_SND_ARRANGE, "He_walkB"  },   // was z_ftL
    { 6, 0x1A, 12, DC_SND_ARRANGE, "He_jump"   },   // was z_ftR
    { 6, 0x1A, 13, DC_SND_ARRANGE, "He_att"    },   // was z_kamu
    { 6, 0x1A, 14, DC_SND_ARRANGE, "He_land"   },   // was z_suzu02
    { 6, 0x1A, 15, DC_SND_ARRANGE, "He_smash"  },   // was z_suzu01
    { 6, 0x1A, 16, DC_SND_ARRANGE, "He_dam"    },   // was z_head
    { 6, 0x1A, 17, DC_SND_ARRANGE, "He_Nout"   },   // was z_Hkick
    { 6, 0x1A, 18, DC_SND_ARRANGE, 0           },   // was z_Ugoron
    { 6, 0x1A, 19, DC_SND_ARRANGE, 0           },   // was z_suzu03

    // ------------------------------------------------------------------
    // No arrange RDT: the room keeps its own file in every mode and the
    // PC row simply has nothing for the enemy the DC spawns there.
    // ------------------------------------------------------------------
    // room 116 - group 0, enemy id 17 - donor ROOM1090
    { 0, 0x16,  0, DC_SND_ANY_DC,  "z_taore"   },   // was nothing
    { 0, 0x16,  1, DC_SND_ANY_DC,  "z_ftL"     },   // was nothing
    { 0, 0x16,  2, DC_SND_ANY_DC,  "z_ftR"     },   // was nothing
    { 0, 0x16,  3, DC_SND_ANY_DC,  "z_kamu"    },   // was nothing
    { 0, 0x16,  4, DC_SND_ANY_DC,  "z_osou"    },   // was nothing
    { 0, 0x16,  5, DC_SND_ANY_DC,  "z_unaruA"  },   // was nothing
    { 0, 0x16,  6, DC_SND_ANY_DC,  "z_head"    },   // was nothing
    { 0, 0x16,  7, DC_SND_ANY_DC,  "z_Hkick"   },   // was nothing
    { 0, 0x16,  8, DC_SND_ANY_DC,  "z_Ugoron"  },   // was nothing
    { 0, 0x16,  9, DC_SND_ANY_DC,  "z_unaruB"  },   // was nothing
    // room 40A - group 0, enemy id 0 - donor ROOM1090
    { 3, 0x0A,  0, DC_SND_ANY_DC,  "z_taore"   },   // was nothing
    { 3, 0x0A,  1, DC_SND_ANY_DC,  "z_ftL"     },   // was nothing
    { 3, 0x0A,  2, DC_SND_ANY_DC,  "z_ftR"     },   // was nothing
    { 3, 0x0A,  3, DC_SND_ANY_DC,  "z_kamu"    },   // was nothing
    { 3, 0x0A,  4, DC_SND_ANY_DC,  "z_osou"    },   // was nothing
    { 3, 0x0A,  5, DC_SND_ANY_DC,  "z_unaruA"  },   // was nothing
    { 3, 0x0A,  6, DC_SND_ANY_DC,  "z_head"    },   // was nothing
    { 3, 0x0A,  7, DC_SND_ANY_DC,  "z_Hkick"   },   // was nothing
    { 3, 0x0A,  8, DC_SND_ANY_DC,  "z_Ugoron"  },   // was nothing
    { 3, 0x0A,  9, DC_SND_ANY_DC,  "z_unaruB"  },   // was nothing
    // room 50A - group 0, enemy ids 0, 1, 17 - donor ROOM1090
    { 4, 0x0A,  0, DC_SND_ANY_DC,  "z_taore"   },   // was nothing
    { 4, 0x0A,  1, DC_SND_ANY_DC,  "z_ftL"     },   // was nothing
    { 4, 0x0A,  2, DC_SND_ANY_DC,  "z_ftR"     },   // was nothing
    { 4, 0x0A,  3, DC_SND_ANY_DC,  "z_kamu"    },   // was nothing
    { 4, 0x0A,  4, DC_SND_ANY_DC,  "z_osou"    },   // was nothing
    { 4, 0x0A,  5, DC_SND_ANY_DC,  "z_unaruA"  },   // was nothing
    { 4, 0x0A,  6, DC_SND_ANY_DC,  "z_head"    },   // was nothing
    { 4, 0x0A,  7, DC_SND_ANY_DC,  "z_Hkick"   },   // was nothing
    { 4, 0x0A,  8, DC_SND_ANY_DC,  "z_Ugoron"  },   // was nothing
    { 4, 0x0A,  9, DC_SND_ANY_DC,  "z_unaruB"  },   // was nothing
    // room 605 - group 0, enemy ids 17, 34 - donor ROOM6010
    { 5, 0x05,  0, DC_SND_ANY_DC,  "HU_walkA"  },   // was nothing
    { 5, 0x05,  1, DC_SND_ANY_DC,  "HU_walkB"  },   // was nothing
    { 5, 0x05,  2, DC_SND_ANY_DC,  "HU_jump"   },   // was nothing
    { 5, 0x05,  3, DC_SND_ANY_DC,  "HU_att"    },   // was nothing
    { 5, 0x05,  4, DC_SND_ANY_DC,  "HU_land"   },   // was nothing
    { 5, 0x05,  5, DC_SND_ANY_DC,  "HU_smash"  },   // was nothing
    { 5, 0x05,  6, DC_SND_ANY_DC,  "HU_dam"    },   // was nothing
    { 5, 0x05,  7, DC_SND_ANY_DC,  "HU_Nout"   },   // was nothing
    // room 616 - group 0, enemy id 17 - donor ROOM1090
    { 5, 0x16,  0, DC_SND_ANY_DC,  "z_taore"   },   // was nothing
    { 5, 0x16,  1, DC_SND_ANY_DC,  "z_ftL"     },   // was nothing
    { 5, 0x16,  2, DC_SND_ANY_DC,  "z_ftR"     },   // was nothing
    { 5, 0x16,  3, DC_SND_ANY_DC,  "z_kamu"    },   // was nothing
    { 5, 0x16,  4, DC_SND_ANY_DC,  "z_osou"    },   // was nothing
    { 5, 0x16,  5, DC_SND_ANY_DC,  "z_unaruA"  },   // was nothing
    { 5, 0x16,  6, DC_SND_ANY_DC,  "z_head"    },   // was nothing
    { 5, 0x16,  7, DC_SND_ANY_DC,  "z_Hkick"   },   // was nothing
    { 5, 0x16,  8, DC_SND_ANY_DC,  "z_Ugoron"  },   // was nothing
    { 5, 0x16,  9, DC_SND_ANY_DC,  "z_unaruB"  },   // was nothing
    // room 713 - group 1, enemy id 6 - donor ROOM3040
    { 6, 0x13, 10, DC_SND_ANY_DC,  "HU_walkA"  },   // was nothing
    { 6, 0x13, 11, DC_SND_ANY_DC,  "HU_walkB"  },   // was nothing
    { 6, 0x13, 12, DC_SND_ANY_DC,  "HU_jump"   },   // was nothing
    { 6, 0x13, 13, DC_SND_ANY_DC,  "HU_att"    },   // was nothing
    { 6, 0x13, 14, DC_SND_ANY_DC,  "HU_land"   },   // was nothing
    { 6, 0x13, 15, DC_SND_ANY_DC,  "HU_smash"  },   // was nothing
    { 6, 0x13, 16, DC_SND_ANY_DC,  "HU_dam"    },   // was nothing
    { 6, 0x13, 17, DC_SND_ANY_DC,  "HU_Nout"   },   // was nothing
};

const DcArrangeSndSlot* dc_arrange_snd_slots(int* count)
{
    if (count) {
        *count = (int)(sizeof(g_dcArrangeSndSlots) / sizeof(g_dcArrangeSndSlots[0]));
    }
    return g_dcArrangeSndSlots;
}
