// ItemTables.h - Director's Cut item data.
//
// GENERATED by tools/gen_dc_item_tables.py - do not edit by hand.
#pragma once

#define DC_ITEM_LOOKUP_BYTES 459
#define DC_ITEM_COMBINE_COUNT 38
#define DC_ITEM_COMBINE_BYTES 454
#define DC_ITEM_IMAGE_TYPE_COUNT 38

// The port's item image-lookup table (g_ItemImageLookupTable) with the DC's
// per-item records applied. The PS1 stores the records 1-based and rotated
// (flags first); this table is in the port's order, so consumers switch tables
// on g_bDcMode with no other change. DC differs from the port at
// 17 item(s).
extern const unsigned char g_dcItemImageLookupTable[DC_ITEM_LOOKUP_BYTES];

// The DC's combine table (SLUS_005.51 0x8008E0CC, 38 entries vs the port's 35):
// each entry is a `count` byte then count 4-byte records, with
// g_dcItemCombinePtrs holding offsets into g_dcItemCombineData. The three extra
// entries are the MOON CREST recipes, so the lookup's combine indices already
// point at the shifted entries - no +3 arithmetic in the consumers.
extern const unsigned char g_dcItemCombineData[DC_ITEM_COMBINE_BYTES];
extern const unsigned char* g_dcItemCombinePtrs[DC_ITEM_COMBINE_COUNT];

// g_ItemImageTypeTable for the DC (SLUS_005.51 0x8008E164, 38 bytes vs the
// port's 35): combine index -> the 1-based ITEM_MIX.PIX row of the sprite for
// the item owning that index, read by menu_item_combine_refresh when a combine
// changes a slot. The DC inserted its three crest recipes at 26..28 and the
// mixed herbs' rows moved +3 with their combine indices, so a combine into the
// assembled MOON CREST (index 0x1C) reloads the crest icon instead of leaving
// the half's sprite in place.
extern const unsigned char g_dcItemImageTypeTable[DC_ITEM_IMAGE_TYPE_COUNT];
