// ItemNames.cpp - Director's Cut item names.
//
// GENERATED by tools/gen_dc_item_names.py - do not edit by hand.
#include "../../Globals.h"
#include "../PrintText.h"              // STR()
#include "ItemNames.h"

static constexpr auto s_dcItemName000 = STR("COMBAT KNIFE\x07");
static constexpr auto s_dcItemName001 = STR("BERETTA\x07");
static constexpr auto s_dcItemName002 = STR("SHOTGUN\x07");
static constexpr auto s_dcItemName003 = STR("COLT PYTHON\x07");
static constexpr auto s_dcItemName004 = STR("FLAMETHROWER\x07");
static constexpr auto s_dcItemName005 = STR("BAZOOKA\x07");
static constexpr auto s_dcItemName006 = STR("R. LAUNCHER\x07");
static constexpr auto s_dcItemName007 = STR("CLIP\x07");
static constexpr auto s_dcItemName008 = STR("SHELLS\x07");
static constexpr auto s_dcItemName009 = STR("LOCKPICK\x07");
static constexpr auto s_dcItemName010 = STR("MAGNUM ROUNDS\x07");
static constexpr auto s_dcItemName011 = STR("FUEL\x07");
static constexpr auto s_dcItemName012 = STR("EXPLOSIVE R.\x07");
static constexpr auto s_dcItemName013 = STR("ACID ROUNDS\x07");
static constexpr auto s_dcItemName014 = STR("FLAME ROUNDS\x07");
static constexpr auto s_dcItemName015 = STR("EMPTY BOTTLE\x07");
static constexpr auto s_dcItemName016 = STR("WATER\x07");
static constexpr auto s_dcItemName017 = STR("UMB No.2\x07");
static constexpr auto s_dcItemName018 = STR("UMB No.4\x07");
static constexpr auto s_dcItemName019 = STR("UMB No.7\x07");
static constexpr auto s_dcItemName020 = STR("UMB No.13\x07");
static constexpr auto s_dcItemName021 = STR("Yellow-6\x07");
static constexpr auto s_dcItemName022 = STR("NP-003\x07");
static constexpr auto s_dcItemName023 = STR("V-JOLT\x07");
static constexpr auto s_dcItemName024 = STR("BROKEN SHOTGUN\x07");
static constexpr auto s_dcItemName025 = STR("SQUARE CRANK\x07");
static constexpr auto s_dcItemName026 = STR("HEX. CRANK\x07");
static constexpr auto s_dcItemName027 = STR("EMBLEM\x07");
static constexpr auto s_dcItemName028 = STR("GOLD EMBLEM\x07");
static constexpr auto s_dcItemName029 = STR("BLUE JEWEL\x07");
static constexpr auto s_dcItemName030 = STR("RED JEWEL\x07");
static constexpr auto s_dcItemName031 = STR("MUSIC NOTES\x07");
static constexpr auto s_dcItemName032 = STR("WOLF MEDAL\x07");
static constexpr auto s_dcItemName033 = STR("EAGLE MEDAL\x07");
static constexpr auto s_dcItemName034 = STR("HERBICIDE\x07");
static constexpr auto s_dcItemName035 = STR("BATTERY\x07");
static constexpr auto s_dcItemName036 = STR("MO DISK\x07");
static constexpr auto s_dcItemName037 = STR("WIND CREST\x07");
static constexpr auto s_dcItemName038 = STR("FLARE\x07");
static constexpr auto s_dcItemName039 = STR("SLIDES\x07");
static constexpr auto s_dcItemName040 = STR("MOON CREST\x07");
static constexpr auto s_dcItemName041 = STR("STAR CREST\x07");
static constexpr auto s_dcItemName042 = STR("SUN CREST\x07");
static constexpr auto s_dcItemName043 = STR("INK RIBBON\x07");
static constexpr auto s_dcItemName044 = STR("LIGHTER\x07");
static constexpr auto s_dcItemName045 = STR("SWORD KEY\x07");
static constexpr auto s_dcItemName046 = STR("ARMOR KEY\x07");
static constexpr auto s_dcItemName047 = STR("SHIELD KEY\x07");
static constexpr auto s_dcItemName048 = STR("HELMET KEY\x07");
static constexpr auto s_dcItemName049 = STR("MASTER KEY\x07");
static constexpr auto s_dcItemName050 = STR("CLOSET KEY\x07");
static constexpr auto s_dcItemName051 = STR("002 KEY\x07");
static constexpr auto s_dcItemName052 = STR("003 KEY\x07");
static constexpr auto s_dcItemName053 = STR("C. ROOM KEY\x07");
static constexpr auto s_dcItemName054 = STR("P. ROOM KEY\x07");
static constexpr auto s_dcItemName055 = STR("DESK KEY\x07");
static constexpr auto s_dcItemName056 = STR("BLANK BOOK\x07");
static constexpr auto s_dcItemName057 = STR("DOOM BOOK 2\x07");
static constexpr auto s_dcItemName058 = STR("DOOM BOOK 1\x07");
static constexpr auto s_dcItemName059 = STR("F.-AID SPRAY\x07");
static constexpr auto s_dcItemName060 = STR("SERUM\x07");
static constexpr auto s_dcItemName061 = STR("RED HERB\x07");
static constexpr auto s_dcItemName062 = STR("GREEN HERB\x07");
static constexpr auto s_dcItemName063 = STR("BLUE HERB\x07");
static constexpr auto s_dcItemName064 = STR("MIXED HERBS\x07");
static constexpr auto s_dcItemName065 = STR("\x07");
static constexpr auto s_dcItemName066 = STR("COM. RADIO\x07");
static constexpr auto s_dcItemName067 = STR("RESEARCHER'S WILL\x07");
static constexpr auto s_dcItemName068 = STR("KEEPER'S DIARY\x07");
static constexpr auto s_dcItemName069 = STR("ORDERS\x07");
static constexpr auto s_dcItemName070 = STR("PASS NUMBER\x07");
static constexpr auto s_dcItemName071 = STR("PLANT42 REPORT\x07");
static constexpr auto s_dcItemName072 = STR("FAX\x07");
static constexpr auto s_dcItemName073 = STR("SCRAPBOOK\x07");
static constexpr auto s_dcItemName074 = STR("SECURITY SYSTEM\x07");
static constexpr auto s_dcItemName075 = STR("RESEARCHER'S LETTER\x07");
static constexpr auto s_dcItemName076 = STR("\\oV-JOLT\" REPORT\x07");
static constexpr auto s_dcItemName077 = STR("BARRY'S PICTURE\x07");
static constexpr auto s_dcItemName078 = STR("PASS CODE01\x07");
static constexpr auto s_dcItemName079 = STR("PASS CODE02\x07");
static constexpr auto s_dcItemName080 = STR("PASS CODE03\x07");
static constexpr auto s_dcItemName081 = STR("BOTANY BOOK\x07");
static constexpr auto s_dcItemName082 = STR("CRANK\x07");
static constexpr auto s_dcItemName083 = STR("CHEMICAL\x07");
static constexpr auto s_dcItemName084 = STR("MANSION KEY\x07");
static constexpr auto s_dcItemName085 = STR("LAB KEY\x07");
static constexpr auto s_dcItemName086 = STR("SPECIAL KEY\x07");
static constexpr auto s_dcItemName087 = STR("DORMITORY KEY\x07");
static constexpr auto s_dcItemName088 = STR("SMALL KEY\x07");
static constexpr auto s_dcItemName089 = STR("RED BOOK\x07");

const unsigned char* g_dcItemNamePointers[DC_ITEM_NAME_COUNT] = {
    (unsigned char*)s_dcItemName000.bytes,    // [  0] COMBAT KNIFE
    (unsigned char*)s_dcItemName001.bytes,    // [  1] BERETTA
    (unsigned char*)s_dcItemName002.bytes,    // [  2] SHOTGUN
    (unsigned char*)s_dcItemName001.bytes,    // [  3] BERETTA
    (unsigned char*)s_dcItemName003.bytes,    // [  4] COLT PYTHON
    (unsigned char*)s_dcItemName004.bytes,    // [  5] FLAMETHROWER
    (unsigned char*)s_dcItemName005.bytes,    // [  6] BAZOOKA
    (unsigned char*)s_dcItemName005.bytes,    // [  7] BAZOOKA
    (unsigned char*)s_dcItemName005.bytes,    // [  8] BAZOOKA
    (unsigned char*)s_dcItemName006.bytes,    // [  9] R. LAUNCHER
    (unsigned char*)s_dcItemName007.bytes,    // [ 10] CLIP
    (unsigned char*)s_dcItemName008.bytes,    // [ 11] SHELLS
    (unsigned char*)s_dcItemName009.bytes,    // [ 12] LOCKPICK
    (unsigned char*)s_dcItemName010.bytes,    // [ 13] MAGNUM ROUNDS
    (unsigned char*)s_dcItemName011.bytes,    // [ 14] FUEL
    (unsigned char*)s_dcItemName012.bytes,    // [ 15] EXPLOSIVE R.
    (unsigned char*)s_dcItemName013.bytes,    // [ 16] ACID ROUNDS
    (unsigned char*)s_dcItemName014.bytes,    // [ 17] FLAME ROUNDS
    (unsigned char*)s_dcItemName015.bytes,    // [ 18] EMPTY BOTTLE
    (unsigned char*)s_dcItemName016.bytes,    // [ 19] WATER
    (unsigned char*)s_dcItemName017.bytes,    // [ 20] UMB No.2
    (unsigned char*)s_dcItemName018.bytes,    // [ 21] UMB No.4
    (unsigned char*)s_dcItemName019.bytes,    // [ 22] UMB No.7
    (unsigned char*)s_dcItemName020.bytes,    // [ 23] UMB No.13
    (unsigned char*)s_dcItemName021.bytes,    // [ 24] Yellow-6
    (unsigned char*)s_dcItemName022.bytes,    // [ 25] NP-003
    (unsigned char*)s_dcItemName023.bytes,    // [ 26] V-JOLT
    (unsigned char*)s_dcItemName024.bytes,    // [ 27] BROKEN SHOTGUN
    (unsigned char*)s_dcItemName025.bytes,    // [ 28] SQUARE CRANK
    (unsigned char*)s_dcItemName026.bytes,    // [ 29] HEX. CRANK
    (unsigned char*)s_dcItemName027.bytes,    // [ 30] EMBLEM
    (unsigned char*)s_dcItemName028.bytes,    // [ 31] GOLD EMBLEM
    (unsigned char*)s_dcItemName029.bytes,    // [ 32] BLUE JEWEL
    (unsigned char*)s_dcItemName030.bytes,    // [ 33] RED JEWEL
    (unsigned char*)s_dcItemName031.bytes,    // [ 34] MUSIC NOTES
    (unsigned char*)s_dcItemName032.bytes,    // [ 35] WOLF MEDAL
    (unsigned char*)s_dcItemName033.bytes,    // [ 36] EAGLE MEDAL
    (unsigned char*)s_dcItemName034.bytes,    // [ 37] HERBICIDE
    (unsigned char*)s_dcItemName035.bytes,    // [ 38] BATTERY
    (unsigned char*)s_dcItemName036.bytes,    // [ 39] MO DISK
    (unsigned char*)s_dcItemName037.bytes,    // [ 40] WIND CREST
    (unsigned char*)s_dcItemName038.bytes,    // [ 41] FLARE
    (unsigned char*)s_dcItemName039.bytes,    // [ 42] SLIDES
    (unsigned char*)s_dcItemName040.bytes,    // [ 43] MOON CREST
    (unsigned char*)s_dcItemName041.bytes,    // [ 44] STAR CREST
    (unsigned char*)s_dcItemName042.bytes,    // [ 45] SUN CREST
    (unsigned char*)s_dcItemName043.bytes,    // [ 46] INK RIBBON
    (unsigned char*)s_dcItemName044.bytes,    // [ 47] LIGHTER
    (unsigned char*)s_dcItemName040.bytes,    // [ 48] MOON CREST
    (unsigned char*)s_dcItemName040.bytes,    // [ 49] MOON CREST
    (unsigned char*)s_dcItemName045.bytes,    // [ 50] SWORD KEY
    (unsigned char*)s_dcItemName046.bytes,    // [ 51] ARMOR KEY
    (unsigned char*)s_dcItemName047.bytes,    // [ 52] SHIELD KEY
    (unsigned char*)s_dcItemName048.bytes,    // [ 53] HELMET KEY
    (unsigned char*)s_dcItemName049.bytes,    // [ 54] MASTER KEY
    (unsigned char*)s_dcItemName050.bytes,    // [ 55] CLOSET KEY
    (unsigned char*)s_dcItemName051.bytes,    // [ 56] 002 KEY
    (unsigned char*)s_dcItemName052.bytes,    // [ 57] 003 KEY
    (unsigned char*)s_dcItemName053.bytes,    // [ 58] C. ROOM KEY
    (unsigned char*)s_dcItemName054.bytes,    // [ 59] P. ROOM KEY
    (unsigned char*)s_dcItemName055.bytes,    // [ 60] DESK KEY
    (unsigned char*)s_dcItemName056.bytes,    // [ 61] BLANK BOOK
    (unsigned char*)s_dcItemName057.bytes,    // [ 62] DOOM BOOK 2
    (unsigned char*)s_dcItemName058.bytes,    // [ 63] DOOM BOOK 1
    (unsigned char*)s_dcItemName059.bytes,    // [ 64] F.-AID SPRAY
    (unsigned char*)s_dcItemName060.bytes,    // [ 65] SERUM
    (unsigned char*)s_dcItemName061.bytes,    // [ 66] RED HERB
    (unsigned char*)s_dcItemName062.bytes,    // [ 67] GREEN HERB
    (unsigned char*)s_dcItemName063.bytes,    // [ 68] BLUE HERB
    (unsigned char*)s_dcItemName064.bytes,    // [ 69] MIXED HERBS
    (unsigned char*)s_dcItemName064.bytes,    // [ 70] MIXED HERBS
    (unsigned char*)s_dcItemName064.bytes,    // [ 71] MIXED HERBS
    (unsigned char*)s_dcItemName064.bytes,    // [ 72] MIXED HERBS
    (unsigned char*)s_dcItemName064.bytes,    // [ 73] MIXED HERBS
    (unsigned char*)s_dcItemName064.bytes,    // [ 74] MIXED HERBS
    (unsigned char*)s_dcItemName065.bytes,    // [ 75] 
    (unsigned char*)s_dcItemName066.bytes,    // [ 76] COM. RADIO
    (unsigned char*)s_dcItemName065.bytes,    // [ 77] 
    (unsigned char*)s_dcItemName065.bytes,    // [ 78] 
    (unsigned char*)s_dcItemName065.bytes,    // [ 79] 
    (unsigned char*)s_dcItemName065.bytes,    // [ 80] 
    (unsigned char*)s_dcItemName065.bytes,    // [ 81] 
    (unsigned char*)s_dcItemName065.bytes,    // [ 82] 
    (unsigned char*)s_dcItemName065.bytes,    // [ 83] 
    (unsigned char*)s_dcItemName065.bytes,    // [ 84] 
    (unsigned char*)s_dcItemName065.bytes,    // [ 85] 
    (unsigned char*)s_dcItemName065.bytes,    // [ 86] 
    (unsigned char*)s_dcItemName065.bytes,    // [ 87] 
    (unsigned char*)s_dcItemName065.bytes,    // [ 88] 
    (unsigned char*)s_dcItemName065.bytes,    // [ 89] 
    (unsigned char*)s_dcItemName065.bytes,    // [ 90] 
    (unsigned char*)s_dcItemName065.bytes,    // [ 91] 
    (unsigned char*)s_dcItemName065.bytes,    // [ 92] 
    (unsigned char*)s_dcItemName065.bytes,    // [ 93] 
    (unsigned char*)s_dcItemName067.bytes,    // [ 94] RESEARCHER'S WILL
    (unsigned char*)s_dcItemName067.bytes,    // [ 95] RESEARCHER'S WILL
    (unsigned char*)s_dcItemName068.bytes,    // [ 96] KEEPER'S DIARY
    (unsigned char*)s_dcItemName069.bytes,    // [ 97] ORDERS
    (unsigned char*)s_dcItemName070.bytes,    // [ 98] PASS NUMBER
    (unsigned char*)s_dcItemName071.bytes,    // [ 99] PLANT42 REPORT
    (unsigned char*)s_dcItemName072.bytes,    // [100] FAX
    (unsigned char*)s_dcItemName073.bytes,    // [101] SCRAPBOOK
    (unsigned char*)s_dcItemName074.bytes,    // [102] SECURITY SYSTEM
    (unsigned char*)s_dcItemName075.bytes,    // [103] RESEARCHER'S LETTER
    (unsigned char*)s_dcItemName076.bytes,    // [104] \\oV-JOLT\" REPORT
    (unsigned char*)s_dcItemName077.bytes,    // [105] BARRY'S PICTURE
    (unsigned char*)s_dcItemName078.bytes,    // [106] PASS CODE01
    (unsigned char*)s_dcItemName079.bytes,    // [107] PASS CODE02
    (unsigned char*)s_dcItemName080.bytes,    // [108] PASS CODE03
    (unsigned char*)s_dcItemName081.bytes,    // [109] BOTANY BOOK
    (unsigned char*)s_dcItemName082.bytes,    // [110] CRANK
    (unsigned char*)s_dcItemName082.bytes,    // [111] CRANK
    (unsigned char*)s_dcItemName083.bytes,    // [112] CHEMICAL
    (unsigned char*)s_dcItemName084.bytes,    // [113] MANSION KEY
    (unsigned char*)s_dcItemName084.bytes,    // [114] MANSION KEY
    (unsigned char*)s_dcItemName084.bytes,    // [115] MANSION KEY
    (unsigned char*)s_dcItemName084.bytes,    // [116] MANSION KEY
    (unsigned char*)s_dcItemName085.bytes,    // [117] LAB KEY
    (unsigned char*)s_dcItemName086.bytes,    // [118] SPECIAL KEY
    (unsigned char*)s_dcItemName087.bytes,    // [119] DORMITORY KEY
    (unsigned char*)s_dcItemName087.bytes,    // [120] DORMITORY KEY
    (unsigned char*)s_dcItemName085.bytes,    // [121] LAB KEY
    (unsigned char*)s_dcItemName088.bytes,    // [122] SMALL KEY
    (unsigned char*)s_dcItemName089.bytes,    // [123] RED BOOK
    (unsigned char*)s_dcItemName057.bytes,    // [124] DOOM BOOK 2
    (unsigned char*)s_dcItemName058.bytes,    // [125] DOOM BOOK 1
    (unsigned char*)s_dcItemName057.bytes,    // [126] DOOM BOOK 2
    (unsigned char*)s_dcItemName058.bytes,    // [127] DOOM BOOK 1
};
