// ItemDescriptions.cpp - Director's Cut item descriptions.
//
// GENERATED by tools/gen_dc_item_descriptions.py - do not edit by hand.
#include "../../Globals.h"
#include "../PrintText.h"              // STR()
#include "ItemDescriptions.h"

static constexpr auto s_dcidesc00 = STR("This doesn't seem to be\\nenough for this mission.");
static constexpr auto s_dcidesc01 = STR("Beretta M92FS. Automatic\\nloaded with 9mm bullets.");
static constexpr auto s_dcidesc02 = STR("Remington M870.\\nA pump-action shotgun.");
static constexpr auto s_dcidesc03 = STR("A beretta M92FS Automatic.\\nCustom edition.");
static constexpr auto s_dcidesc04 = STR("Powerful gun can be loaded\\nwith .357 magnum rounds.");
static constexpr auto s_dcidesc05 = STR("Can throw flame for 9 sec.\\nwith max. fuel.");
static constexpr auto s_dcidesc06 = STR("A launcher can be loaded\\nwith various rounds.");
static constexpr auto s_dcidesc07 = STR("One shot can destroy any\\ntarget.");
static constexpr auto s_dcidesc08 = STR("Clip for Beretta.");
static constexpr auto s_dcidesc09 = STR("Shells for the shotgun.");
static constexpr auto s_dcidesc10 = STR("More powerful than magnum\\nrounds.  For the C.Python.");
static constexpr auto s_dcidesc11 = STR(".357 magnum rounds.\\nFor the Colt Python.");
static constexpr auto s_dcidesc12 = STR("Fuel for the flamethrower.");
static constexpr auto s_dcidesc13 = STR("Powerful rounds for the\\nBazooka.");
static constexpr auto s_dcidesc14 = STR("A glass bottle to put\\nchemicals in.");
static constexpr auto s_dcidesc15 = STR("There's water in the\\nbottle.");
static constexpr auto s_dcidesc16 = STR("This is needed to generate\\nV-JOLT.");
static constexpr auto s_dcidesc17 = STR("This is not the chemical I\\nneed.");
static constexpr auto s_dcidesc18 = STR("Now I can destroy that ivy\\nmonster.");
static constexpr auto s_dcidesc19 = STR("It's too dangerous to fire!\\nDose it have another use?");
static constexpr auto s_dcidesc20 = STR("Nothing important.");
static constexpr auto s_dcidesc21 = STR("There's a scratch.\\nSomeone may have used it.");
static constexpr auto s_dcidesc22 = STR("It's shining beautifully.");
static constexpr auto s_dcidesc23 = STR("The title is \\oMoonlight\\nSonata\".");
static constexpr auto s_dcidesc24 = STR("A medal from the\\nsecond Doom Book.");
static constexpr auto s_dcidesc25 = STR("A medal from the\\nfirst Doom Book.");
static constexpr auto s_dcidesc26 = STR("Now I can move the\\nelevator.");
static constexpr auto s_dcidesc27 = STR("It seems to be a start-up \\ndisk.");
static constexpr auto s_dcidesc28 = STR("It represents wind.");
static constexpr auto s_dcidesc29 = STR("I can signal Brad with this.");
static constexpr auto s_dcidesc30 = STR("It seems to be some kind\\nof research report.");
static constexpr auto s_dcidesc31 = STR("A carving of the moon.");
static constexpr auto s_dcidesc32 = STR("A carving of the star.");
static constexpr auto s_dcidesc33 = STR("A carving of the sun.");
static constexpr auto s_dcidesc34 = STR("It's used with a\\ntypewriter.");
static constexpr auto s_dcidesc35 = STR("Some fluid is left.");
static constexpr auto s_dcidesc36 = STR("I can heal any wound with\\nthis.");
static constexpr auto s_dcidesc37 = STR("Only one dose is left.");
static constexpr auto s_dcidesc38 = STR("It's a local herb.");
static constexpr auto s_dcidesc39 = STR("It's a mixture of green\\nand red herbs.");
static constexpr auto s_dcidesc40 = STR("It's a mixture of 2 green\\nherbs.");
static constexpr auto s_dcidesc41 = STR("It's a mixture of green\\nand blue herbs.");
static constexpr auto s_dcidesc42 = STR("It's a mixture of green,\\nblue and red herbs.");
static constexpr auto s_dcidesc43 = STR("It's a mixture of 3 green\\nherbs.");
static constexpr auto s_dcidesc44 = STR("It's a mixture of 2 green\\nherbs and blue herb.");
static constexpr auto s_dcidesc45 = STR("The battery is still\\ncharged.");
unsigned char* g_dcItemDescriptions[DC_ITEM_DESCRIPTION_COUNT] = {
    (unsigned char*)s_dcidesc00.bytes,  // [0x00] item 0x01
    (unsigned char*)s_dcidesc01.bytes,  // [0x01] item 0x02
    (unsigned char*)s_dcidesc02.bytes,  // [0x02] item 0x03
    (unsigned char*)s_dcidesc03.bytes,  // [0x03] item 0x04
    (unsigned char*)s_dcidesc04.bytes,  // [0x04] item 0x05
    (unsigned char*)s_dcidesc05.bytes,  // [0x05] item 0x06
    (unsigned char*)s_dcidesc06.bytes,  // [0x06] item 0x07
    (unsigned char*)s_dcidesc06.bytes,  // [0x07] item 0x08
    (unsigned char*)s_dcidesc06.bytes,  // [0x08] item 0x09
    (unsigned char*)s_dcidesc07.bytes,  // [0x09] item 0x0a
    (unsigned char*)s_dcidesc08.bytes,  // [0x0a] item 0x0b
    (unsigned char*)s_dcidesc09.bytes,  // [0x0b] item 0x0c
    (unsigned char*)s_dcidesc10.bytes,  // [0x0c] item 0x0d
    (unsigned char*)s_dcidesc11.bytes,  // [0x0d] item 0x0e
    (unsigned char*)s_dcidesc12.bytes,  // [0x0e] item 0x0f
    (unsigned char*)s_dcidesc13.bytes,  // [0x0f] item 0x10
    (unsigned char*)s_dcidesc13.bytes,  // [0x10] item 0x11
    (unsigned char*)s_dcidesc13.bytes,  // [0x11] item 0x12
    (unsigned char*)s_dcidesc14.bytes,  // [0x12] item 0x13
    (unsigned char*)s_dcidesc15.bytes,  // [0x13] item 0x14
    (unsigned char*)s_dcidesc16.bytes,  // [0x14] item 0x15
    (unsigned char*)s_dcidesc16.bytes,  // [0x15] item 0x16
    (unsigned char*)s_dcidesc17.bytes,  // [0x16] item 0x17
    (unsigned char*)s_dcidesc17.bytes,  // [0x17] item 0x18
    (unsigned char*)s_dcidesc17.bytes,  // [0x18] item 0x19
    (unsigned char*)s_dcidesc17.bytes,  // [0x19] item 0x1a
    (unsigned char*)s_dcidesc18.bytes,  // [0x1a] item 0x1b
    (unsigned char*)s_dcidesc19.bytes,  // [0x1b] item 0x1c
    (unsigned char*)s_dcidesc20.bytes,  // [0x1c] item 0x1d
    (unsigned char*)s_dcidesc20.bytes,  // [0x1d] item 0x1e
    (unsigned char*)s_dcidesc21.bytes,  // [0x1e] item 0x1f
    (unsigned char*)s_dcidesc21.bytes,  // [0x1f] item 0x20
    (unsigned char*)s_dcidesc22.bytes,  // [0x20] item 0x21
    (unsigned char*)s_dcidesc22.bytes,  // [0x21] item 0x22
    (unsigned char*)s_dcidesc23.bytes,  // [0x22] item 0x23
    (unsigned char*)s_dcidesc24.bytes,  // [0x23] item 0x24
    (unsigned char*)s_dcidesc25.bytes,  // [0x24] item 0x25
    (unsigned char*)s_dcidesc20.bytes,  // [0x25] item 0x26
    (unsigned char*)s_dcidesc26.bytes,  // [0x26] item 0x27
    (unsigned char*)s_dcidesc27.bytes,  // [0x27] item 0x28
    (unsigned char*)s_dcidesc28.bytes,  // [0x28] item 0x29
    (unsigned char*)s_dcidesc29.bytes,  // [0x29] item 0x2a
    (unsigned char*)s_dcidesc30.bytes,  // [0x2a] item 0x2b
    (unsigned char*)s_dcidesc31.bytes,  // [0x2b] item 0x2c
    (unsigned char*)s_dcidesc32.bytes,  // [0x2c] item 0x2d
    (unsigned char*)s_dcidesc33.bytes,  // [0x2d] item 0x2e
    (unsigned char*)s_dcidesc34.bytes,  // [0x2e] item 0x2f
    (unsigned char*)s_dcidesc35.bytes,  // [0x2f] item 0x30
    (unsigned char*)s_dcidesc20.bytes,  // [0x30] item 0x31
    (unsigned char*)s_dcidesc20.bytes,  // [0x31] item 0x32
    (unsigned char*)s_dcidesc20.bytes,  // [0x32] item 0x33
    (unsigned char*)s_dcidesc20.bytes,  // [0x33] item 0x34
    (unsigned char*)s_dcidesc20.bytes,  // [0x34] item 0x35
    (unsigned char*)s_dcidesc20.bytes,  // [0x35] item 0x36
    (unsigned char*)s_dcidesc20.bytes,  // [0x36] item 0x37
    (unsigned char*)s_dcidesc20.bytes,  // [0x37] item 0x38
    (unsigned char*)s_dcidesc20.bytes,  // [0x38] item 0x39
    (unsigned char*)s_dcidesc20.bytes,  // [0x39] item 0x3a
    (unsigned char*)s_dcidesc31.bytes,  // [0x3a] item 0x3b
    (unsigned char*)s_dcidesc20.bytes,  // [0x3b] item 0x3c
    (unsigned char*)s_dcidesc20.bytes,  // [0x3c] item 0x3d
    (unsigned char*)s_dcidesc20.bytes,  // [0x3d] item 0x3e
    (unsigned char*)s_dcidesc20.bytes,  // [0x3e] item 0x3f
    (unsigned char*)s_dcidesc20.bytes,  // [0x3f] item 0x40
    (unsigned char*)s_dcidesc36.bytes,  // [0x40] item 0x41
    (unsigned char*)s_dcidesc37.bytes,  // [0x41] item 0x42
    (unsigned char*)s_dcidesc38.bytes,  // [0x42] item 0x43
    (unsigned char*)s_dcidesc38.bytes,  // [0x43] item 0x44
    (unsigned char*)s_dcidesc38.bytes,  // [0x44] item 0x45
    (unsigned char*)s_dcidesc39.bytes,  // [0x45] item 0x46
    (unsigned char*)s_dcidesc40.bytes,  // [0x46] item 0x47
    (unsigned char*)s_dcidesc41.bytes,  // [0x47] item 0x48
    (unsigned char*)s_dcidesc42.bytes,  // [0x48] item 0x49
    (unsigned char*)s_dcidesc43.bytes,  // [0x49] item 0x4a
    (unsigned char*)s_dcidesc44.bytes,  // [0x4a] item 0x4b
    (unsigned char*)s_dcidesc20.bytes,  // [0x4b] item 0x4c
    (unsigned char*)s_dcidesc45.bytes,  // [0x4c] item 0x4d
    (unsigned char*)s_dcidesc45.bytes,  // [0x4d] item 0x4e
    (unsigned char*)s_dcidesc45.bytes,  // [0x4e] item 0x4f
};
