// WeaponDamageTables.h - Director's Cut per-mode weapon damage.
//
// GENERATED by tools/gen_dc_damage_tables.py - do not edit by hand.
#pragma once

#define DC_WEAPON_DAMAGE_RECORDS 200

// Each record is one (enemy, weapon) pair, indexed weaponAdj + enemyType * 10
// exactly like g_weaponHitRecordsFirstRun: rows are enemies, columns are the ten
// weapon slots (the header comment above row 0 in the .cpp lists them).
//
// The DC's slot 3 (item 4) is its Beretta M92FS custom - the USA build's slot 3
// is the unobtainable Colt Python that takes DumDum rounds, and the DC gives
// that item id to the Beretta. Slot 4 (item 5) is the live Colt Python, magnum
// rounds; the ADVANCED Beretta promotion switches to slot 3, not to slot 4.
//
// Damage columns from SLUS_005.51 apply_weapon_damage (0x800120e8): TRAINING is
// 0x8008B59A and ADVANCED 0x8008BEFA. The STANDARD column is the port's existing
// g_weaponHitRecordsFirstRun damage field (verified equal to the DC's
// 0x8008AC3A column), and ADVANCED* uses that same STANDARD column, matching the
// PS1's `(status & 0x30000) == 0x20000` test.
extern const short g_dcWeaponDamageTraining[DC_WEAPON_DAMAGE_RECORDS];
extern const short g_dcWeaponDamageAdvanced[DC_WEAPON_DAMAGE_RECORDS];

// 0x8008C854: the ADVANCED Beretta roll, tested as `table[rand() & 0xF] != 0`
// (2 of 16 entries non-zero -> ~1/8). Bit i of the mask is set when
// entry i is non-zero.
#define DC_BERETTA_ROLL_MASK 0x4001u
