// WeaponDamageTables.cpp - Director's Cut per-mode weapon damage.
//
// GENERATED by tools/gen_dc_damage_tables.py - do not edit by hand.
// See WeaponDamageTables.h for the provenance of the values. Rows are enemies,
// columns are weapon slots.
#include "WeaponDamageTables.h"

// TRAINING - PS1 0x8008B59A damage column
const short g_dcWeaponDamageTraining[200] = {
    // columns, in order: knife, handgun, shotgun, beretta custom (M92FS, item 4), python (magnum), flamethrower, GL explosive, GL acid, GL flame, rocket launcher
        11,     12,     53,     50,    130,     20,    201,     95,     95,    900,   // 0x00 ENEMY_ZOMBIE
        11,     12,     53,     50,    130,     20,    201,     95,     95,    900,   // 0x01 ENEMY_ZOMBIE_NAKED
        34,     27,     50,     60,    130,     20,    200,    100,    100,    900,   // 0x02 ENEMY_CERBERUS
        14,     24,     60,     40,    130,     20,    100,    100,    200,    900,   // 0x03 ENEMY_WEB_SPINNER
        18,     18,     42,     50,     70,     26,     70,     70,    205,    900,   // 0x04 ENEMY_BLACK_TIGER
        60,     60,     60,     50,    130,     20,    200,     60,     60,    900,   // 0x05 ENEMY_CROW
        20,     27,     40,     40,    130,     32,    100,    200,    100,    900,   // 0x06 ENEMY_HUNTER
        20,     30,     60,     70,    130,     20,    200,     80,     80,    900,   // 0x07 ENEMY_WASP
        20,     20,     30,     38,     74,     20,     60,     45,    150,    900,   // 0x08 ENEMY_PLANT42
        22,     22,     32,     40,    130,     20,    200,     62,     62,    900,   // 0x09 ENEMY_CHIMERA
        60,     60,     60,     50,    130,     30,    200,     60,     60,    900,   // 0x0A ENEMY_ADDER
         0,      0,      0,      0,      0,      0,      0,      0,      0,      0,   // 0x0B ENEMY_NEPTUNE
        24,     20,     30,     50,     80,     20,    100,    100,    100,    900,   // 0x0C ENEMY_TYRANT_1
        26,     30,     40,     40,     80,     20,     80,    130,     50,    900,   // 0x0D ENEMY_YAWN_1
         0,      0,      0,      0,      0,      0,      0,      0,      0,      0,   // 0x0E ENEMY_PLANT42_ROOTS
         0,      0,      0,      0,      0,      0,      0,      0,      0,      0,   // 0x0F ENEMY_MONSTER_PLANT
        24,     20,     30,     50,     80,     20,    100,    100,    100,    900,   // 0x10 ENEMY_TYRANT_2
        14,     15,     53,     50,    130,     20,    201,     95,     95,    900,   // 0x11 ENEMY_ZOMBIE_VARIANT
        26,     30,     40,     40,     80,     20,     80,    130,     50,    900,   // 0x12 ENEMY_YAWN_2
        10,      0,      0,      0,      0,      2,     30,     30,     30,    900,   // 0x13 ENEMY_SPIDER_WEB
};

// ADVANCED - PS1 0x8008BEFA damage column
const short g_dcWeaponDamageAdvanced[200] = {
    // columns, in order: knife, handgun, shotgun, beretta custom (M92FS, item 4), python (magnum), flamethrower, GL explosive, GL acid, GL flame, rocket launcher
         8,      9,     34,     50,     60,     20,    201,     70,     70,    900,   // 0x00 ENEMY_ZOMBIE
         8,      9,     34,     50,     60,     20,    201,     70,     70,    900,   // 0x01 ENEMY_ZOMBIE_NAKED
        30,     20,     35,     60,     60,     20,    200,     90,     90,    900,   // 0x02 ENEMY_CERBERUS
        10,     15,     24,     30,     40,     20,    100,    100,    200,    900,   // 0x03 ENEMY_WEB_SPINNER
        10,     12,     20,     50,     70,     20,     50,     50,    103,    900,   // 0x04 ENEMY_BLACK_TIGER
        50,     26,     50,     50,     50,     20,    200,     60,     60,    900,   // 0x05 ENEMY_CROW
        16,     14,     25,     40,     80,     20,     50,     80,     50,    900,   // 0x06 ENEMY_HUNTER
        20,     30,     60,     70,     70,     20,    200,     80,     80,    900,   // 0x07 ENEMY_WASP
        15,     10,     20,     38,     20,     20,     40,     40,    150,    900,   // 0x08 ENEMY_PLANT42
        10,     12,     20,     40,     41,     20,     60,     60,    100,    900,   // 0x09 ENEMY_CHIMERA
        20,     20,     40,     50,     50,     30,    200,     60,     60,    900,   // 0x0A ENEMY_ADDER
         0,      0,      0,      0,      0,      0,      0,      0,      0,      0,   // 0x0B ENEMY_NEPTUNE
        10,     15,     20,     50,     40,     20,     35,     35,     35,    900,   // 0x0C ENEMY_TYRANT_1
        15,     18,     15,     40,     60,     20,     60,    120,     60,    900,   // 0x0D ENEMY_YAWN_1
         0,      0,      0,      0,      0,      0,      0,      0,      0,      0,   // 0x0E ENEMY_PLANT42_ROOTS
         0,      0,      0,      0,      0,      0,      0,      0,      0,      0,   // 0x0F ENEMY_MONSTER_PLANT
        10,     15,     20,     50,     40,     20,     35,     35,     35,    900,   // 0x10 ENEMY_TYRANT_2
         8,      9,     34,     50,     60,     20,    201,     70,     70,    900,   // 0x11 ENEMY_ZOMBIE_VARIANT
        15,     18,     15,     40,     60,     20,     60,    120,     60,    900,   // 0x12 ENEMY_YAWN_2
         6,      0,      0,      0,      0,      2,     10,     20,     30,    900,   // 0x13 ENEMY_SPIDER_WEB
};
