#!/usr/bin/env python3
"""gen_ps1_manifest.py - bake the 1996 PS1 release into the asset migrator.

The Director's Cut disc carries the whole game, so most of its rooms, models and
backgrounds are the 1996 originals it never touched. Those must NOT go into the
DC overlay: the base tree's copy of the same file is that same 1996 file plus
the PC release's own fixes, so shipping the PS1 one shadows them. Room 715's
floating jewel was exactly that - the PC scripts hide the model with
model_flag_set and the 1996 file leaves it visible.

Nothing on the DC disc says which files it changed. The ISO9660 stamps look like
they might (ROOM3020 carries an individual 1997-08-19 time, ROOM7150 sits in a
bulk 1997-08-21 batch) but cross-tabbing all 269 stage rooms puts 111 changed
and 120 unchanged files in that same bulk stamp - they are mastering batches,
not build markers. The only way to tell is to diff against the 1996 release, so
this script bakes that release's fingerprints into the tool and the migration
needs no second disc.

Usage:
    python tools/gen_ps1_manifest.py <1996 PS1 tree> [-o <header>]

`<1996 PS1 tree>` is the folder holding STAGE1..STAGE7, ENEMY, PLAYERS, ITEM_M1,
ITEM_M2 and DATA (an extracted SLUS-00170 disc). Output defaults to
tools/asset_migrator/src/core/Ps1Manifest.h.

Only size + FNV-1a-64 are stored, not the bytes: the table is a fingerprint of
769 files in ~30 KB of source. A DC file whose name is in the table but whose
size or hash differs is DC content and is kept, so an unrecognised disc revision
degrades to "migrate everything", never to "drop something we should not have".
"""
import argparse
import os
import sys

# The folders the overlay's filter consults, spelled as they are on the disc.
FOLDERS = ('STAGE1', 'STAGE2', 'STAGE3', 'STAGE4', 'STAGE5', 'STAGE6',
           'STAGE7', 'ENEMY', 'PLAYERS', 'ITEM_M1', 'ITEM_M2', 'DATA')

FNV_OFFSET = 0xCBF29CE484222325
FNV_PRIME = 0x100000001B3
MASK64 = 0xFFFFFFFFFFFFFFFF


def fnv1a64(data):
    """Must match fnv1a64() in DcOverlay.cpp byte for byte."""
    h = FNV_OFFSET
    for b in data:
        h = ((h ^ b) * FNV_PRIME) & MASK64
    return h


def find_ci(root, name):
    """The real spelling of `name` under `root`, or None."""
    if not os.path.isdir(root):
        return None
    low = name.lower()
    for f in os.listdir(root):
        if f.lower() == low:
            return os.path.join(root, f)
    return None


def collect(tree):
    rows = []
    for folder in FOLDERS:
        d = find_ci(tree, folder)
        if d is None:
            print('  %-8s not found, skipped' % folder, file=sys.stderr)
            continue
        n = 0
        for name in sorted(os.listdir(d)):
            p = os.path.join(d, name)
            if not os.path.isfile(p):
                continue
            with open(p, 'rb') as f:
                data = f.read()
            rows.append((folder, name.upper(), len(data), fnv1a64(data)))
            n += 1
        print('  %-8s %4d file(s)' % (folder, n), file=sys.stderr)
    # Sorted so the generated table can be binary-searched.
    rows.sort(key=lambda r: (r[0], r[1]))
    return rows


HEADER = '''#pragma once
// GENERATED by tools/gen_ps1_manifest.py - do not edit by hand.
//
// Fingerprints of the 1996 PS1 release (SLUS-00170), the reference that tells
// the DC overlay which of the Director's Cut disc's files are actually the DC's
// and which are the 1996 originals it left alone. Only the latter may be left
// out of the overlay; see leaveToBaseTree() in DcOverlay.cpp for why that
// matters and gen_ps1_manifest.py for why nothing on the DC disc can answer it.
//
// Size + FNV-1a-64, sorted by (folder, name) so lookup is a binary search. A
// file whose name is here but whose size or hash differs is DC content and is
// kept, so an unrecognised disc revision degrades to migrating everything.

#include <cstddef>
#include <cstdint>

namespace re1 {

struct Ps1ManifestEntry {
    const char* folder;  // disc spelling: STAGE1.., ENEMY, PLAYERS, ITEM_M*, DATA
    const char* name;    // upper case, as stored on the disc
    uint32_t size;
    uint64_t hash;       // FNV-1a-64 over the whole file
};

inline constexpr Ps1ManifestEntry kPs1Manifest[] = {
%s};

inline constexpr size_t kPs1ManifestCount =
    sizeof(kPs1Manifest) / sizeof(kPs1Manifest[0]);

}  // namespace re1
'''


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('tree', help='extracted 1996 PS1 release (SLUS-00170)')
    ap.add_argument('-o', '--out', default=os.path.join(
        os.path.dirname(os.path.abspath(__file__)),
        'asset_migrator', 'src', 'core', 'Ps1Manifest.h'))
    args = ap.parse_args()

    if not os.path.isdir(args.tree):
        sys.exit('not a folder: %s' % args.tree)

    print('reading %s' % args.tree, file=sys.stderr)
    rows = collect(args.tree)
    if not rows:
        sys.exit('nothing collected - is that the right tree?')

    body = ''.join(
        '    {"%s", "%s", %du, %#018xull},\n' % (f, n, sz, h)
        for f, n, sz, h in rows)
    with open(args.out, 'w', encoding='utf-8', newline='\n') as fh:
        fh.write(HEADER % body)
    print('wrote %s (%d entries)' % (args.out, len(rows)), file=sys.stderr)


if __name__ == '__main__':
    main()
