#!/usr/bin/env python3
"""gen_dc_damage_tables.py - emit the Director's Cut weapon-damage tables.

The DC's apply_weapon_damage (SLUS_005.51 0x800120e8) picks the damage short
from one of three columns instead of the single table the USA build has:

    iVar5 = weaponAdj * 12 + enemyType * 120          (same indexing as the port)
    if (g_status_flags & 0x40000)                     TRAINING  -> 0x8008B59A
    else if ((g_status_flags & 0x30000) == 0x20000)   ADVANCED  -> 0x8008BEFA
    else                                              STANDARD  -> 0x8008AC3A

Each column is the record's damage field (base + 6 + i*12, i = 0..199). The
knockback/type/data/hit fields always come from the STANDARD table, so only the
damage differs per mode - and the DC has **no second-playthrough damage table**
(its function never tests the playthrough flag).

The DC's ADVANCED Beretta roll table is 0x8008C854: apply_weapon_damage promotes
weapon 2 to the Magnum row when `(status & 0x20000) && weaponAdj == 1 &&
table[rand() & 0xF] != 0`.

The values live only in the PS1 program, which is not in this repo, so they are
read from the running Ghidra bridge:

    python tools/gen_dc_damage_tables.py            # prints + verifies
    python tools/gen_dc_damage_tables.py --write    # rewrites the C file

The STANDARD column is checked against the port's own USA table
(WeaponDamage.cpp g_weaponHitRecordsFirstRun), which must match exactly.
"""
import argparse
import json
import os
import re
import sys
import urllib.request

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BRIDGE = 'http://127.0.0.1:8089/read_memory'
PROGRAM = 'SLUS_005.51'
OUT = os.path.join(REPO, 'src', 'game', 'dc', 'WeaponDamageTables.cpp')
OUT_H = os.path.join(REPO, 'src', 'game', 'dc', 'WeaponDamageTables.h')
USA_SRC = os.path.join(REPO, 'src', 'game', 'WeaponDamage.cpp')

RECORDS = 200           # 20 enemy types x 10 weapon slots
RECORD_SIZE = 12
DAMAGE_OFF = 6

# Column bases (the record start; the damage short sits at +6).
COLUMNS = {
    'stand': 0x8008AC34,
    'train': 0x8008B594,
    'adv':   0x8008BEF4,
}
BERETTA_LUCK = (0x8008C854, 16)


def fetch(address, length):
    url = f'{BRIDGE}?program={PROGRAM}&address={hex(address)}&length={length}'
    with urllib.request.urlopen(url, timeout=30) as r:
        return bytes(json.load(r)['data'])


def damage_column(base):
    raw = fetch(base, RECORDS * RECORD_SIZE)
    return [raw[i * RECORD_SIZE + DAMAGE_OFF] |
            (raw[i * RECORD_SIZE + DAMAGE_OFF + 1] << 8)
            for i in range(RECORDS)]


def usa_damage_column():
    """Damage field of the port's first-run table, for the STANDARD check."""
    text = open(USA_SRC, encoding='utf-8').read()
    body = text.split('g_weaponHitRecordsFirstRun[200] = {', 1)[1]
    body = body.split('\n};', 1)[0]
    out = []
    for m in re.finditer(r'^\s*\{\s*(-?\d+)\s*,\s*(-?\d+)\s*,\s*(-?\d+)\s*,\s*(-?\d+)',
                         body, re.M):
        out.append(int(m.group(4)))
    return out


def usa_table_labels():
    """(weapon names, enemy labels) as written in the port's table comments.

    The first enemy block's trailing comments name the ten weapon slots in
    record order; the `// ---- 0xNN NAME ----` lines name each enemy block.
    """
    text = open(USA_SRC, encoding='utf-8').read()
    body = text.split('g_weaponHitRecordsFirstRun[200] = {', 1)[1]
    body = body.split('\n};', 1)[0]

    weapons, enemies = [], []
    for line in body.splitlines():
        m = re.match(r'\s*//\s*-+\s*(0x[0-9A-Fa-f]+)\s+(\S+)\s*-+', line)
        if m:
            enemies.append(f'{m.group(1)} {m.group(2)}')
            continue
        m = re.match(r'^\s*\{\s*-?\d+\s*,.*\}\s*,\s*//\s*(.+?)\s*$', line)
        if m and len(weapons) < 10:
            weapons.append(m.group(1))
    return weapons, enemies


def emit(columns, luck_mask, weapons, enemies):
    # Columns are the weapon slots (in weapons_ranges order), rows are the enemy
    # types, so the weapon list is written once above row 0 and each row is
    # labelled with its enemy. Both are read from the port's own table comments
    # so the generated file stays in sync with the port naming.
    legend = ', '.join(weapons) if weapons else 'the ten weapon slots'

    def c_array(name, values, heading):
        lines = [f'// {heading}', f'const short {name}[{RECORDS}] = {{']
        lines.append(f'    // columns, in order: {legend}')
        for row in range(RECORDS // 10):
            label = enemies[row] if row < len(enemies) else f'enemy {row:#04x}'
            vals = ', '.join(f'{v:6d}' for v in values[row * 10:(row + 1) * 10])
            lines.append(f'    {vals},   // {label}')
        lines.append('};')
        return '\n'.join(lines)

    header = f'''// WeaponDamageTables.h - Director's Cut per-mode weapon damage.
//
// GENERATED by tools/gen_dc_damage_tables.py - do not edit by hand.
#pragma once

#define DC_WEAPON_DAMAGE_RECORDS {RECORDS}

// Each record is one (enemy, weapon) pair, indexed weaponAdj + enemyType * 10
// exactly like g_weaponHitRecordsFirstRun: rows are enemies, columns are the ten
// weapon slots (the header comment above row 0 in the .cpp lists them).
//
// The DC's slot 3 (item 4) is its Beretta M92FS custom - the USA build's slot 3
// is the unobtainable Colt Python that takes DumDum rounds, and the DC gives
// that item id to the Beretta. Slot 4 (item 5) is the live Colt Python, magnum
// rounds; the ADVANCED Beretta promotion switches to slot 3, not to slot 4.
//
// Damage columns from SLUS_005.51 apply_weapon_damage (0x800120e8): TRAINING is
// 0x8008B59A and ADVANCED 0x8008BEFA. The STANDARD column is the port's existing
// g_weaponHitRecordsFirstRun damage field (verified equal to the DC's
// 0x8008AC3A column), and ADVANCED* uses that same STANDARD column, matching the
// PS1's `(status & 0x30000) == 0x20000` test.
extern const short g_dcWeaponDamageTraining[DC_WEAPON_DAMAGE_RECORDS];
extern const short g_dcWeaponDamageAdvanced[DC_WEAPON_DAMAGE_RECORDS];

// 0x8008C854: the ADVANCED Beretta roll, tested as `table[rand() & 0xF] != 0`
// ({bin(luck_mask).count("1")} of 16 entries non-zero -> ~1/8). Bit i of the mask is set when
// entry i is non-zero.
#define DC_BERETTA_ROLL_MASK 0x{luck_mask:04X}u
'''

    source = f'''// WeaponDamageTables.cpp - Director's Cut per-mode weapon damage.
//
// GENERATED by tools/gen_dc_damage_tables.py - do not edit by hand.
// See WeaponDamageTables.h for the provenance of the values. Rows are enemies,
// columns are weapon slots.
#include "WeaponDamageTables.h"

{c_array('g_dcWeaponDamageTraining', columns['train'], 'TRAINING - PS1 0x8008B59A damage column')}

{c_array('g_dcWeaponDamageAdvanced', columns['adv'], 'ADVANCED - PS1 0x8008BEFA damage column')}
'''
    return header, source


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('--write', action='store_true', help='rewrite the C file')
    args = ap.parse_args()

    try:
        columns = {name: damage_column(base) for name, base in COLUMNS.items()}
        luck = fetch(*BERETTA_LUCK)
    except Exception as e:                      # noqa: BLE001
        print(f'bridge read failed: {type(e).__name__}: {e}', file=sys.stderr)
        print('the Ghidra bridge must be running with SLUS_005.51 open', file=sys.stderr)
        return 1

    usa = usa_damage_column()
    ok = (len(usa) == RECORDS and usa == columns['stand'])
    print(f'STANDARD column == port USA table: {ok}  '
          f'(port records parsed: {len(usa)})')
    if not ok:
        for i, (a, b) in enumerate(zip(usa, columns['stand'])):
            if a != b:
                print(f'  first mismatch record {i} (enemy {i // 10}, weapon {i % 10}): '
                      f'port {a} vs DC {b}')
                break

    for name in ('train', 'adv'):
        diffs = [i for i in range(RECORDS) if columns[name][i] != columns['stand'][i]]
        print(f'{name:5s}: {len(diffs):3d} differing records'
              + (f', e.g. {diffs[:8]}' if diffs else ''))

    mask = 0
    for i, b in enumerate(luck):
        if b:
            mask |= 1 << i
    print(f'beretta roll table: mask {mask:#06x} ({bin(mask).count("1")} of 16 non-zero)')

    if not ok:
        print('refusing to write: the STANDARD check failed', file=sys.stderr)
        return 1

    weapons, enemies = usa_table_labels()
    print(f'weapon slots ({len(weapons)}): ' + ', '.join(weapons))
    print(f'enemy labels ({len(enemies)}): ' + ', '.join(enemies[:3]) + ' ...')
    if len(weapons) != 10 or len(enemies) != RECORDS // 10:
        print('could not read the weapon/enemy labels from WeaponDamage.cpp',
              file=sys.stderr)
        return 1

    # The DC's slot 3 is its Beretta M92FS custom (item 4), where the USA build
    # has the unobtainable DumDum Python; everything else matches. Swap the label
    # just for the DC header so it is not misleading.
    DC_SLOT3 = 'beretta custom (M92FS, item 4)'
    print(f'DC slot 3 label: {weapons[3]!r} -> {DC_SLOT3!r}')
    weapons = list(weapons)
    weapons[3] = DC_SLOT3

    text, source = emit(columns, mask, weapons, enemies)
    if args.write:
        with open(OUT_H, 'w', encoding='utf-8', newline='\n') as f:
            f.write(text)
        with open(OUT, 'w', encoding='utf-8', newline='\n') as f:
            f.write(source)
        print('wrote ' + os.path.relpath(OUT_H, REPO) + ' and ' + os.path.relpath(OUT, REPO))
    else:
        print('(--write not given: C files not modified)')
    return 0


if __name__ == '__main__':
    sys.exit(main())
